export const DEMO_SHOWS = [
  {
    id: 'slow-horses',
    source: 'manual',
    sourceShowId: null,
    title: 'Slow Horses',
    section: 'watching',
    sortOrder: 0,
    withPriya: true,
    currentSeason: 6,
    expanded: true,
    archivedAt: null,
    availableSeasonNumber: null,
    seasons: [{ seasonNumber: 6 }],
    episodes: [
      { id: 'sh-1', episodeNumber: 1, title: 'Episode 1', runtimeMinutes: 46, watched: true },
      { id: 'sh-2', episodeNumber: 2, title: 'Episode 2', runtimeMinutes: 44, watched: true },
      { id: 'sh-3', episodeNumber: 3, title: 'Episode 3', runtimeMinutes: 48, watched: true },
      { id: 'sh-4', episodeNumber: 4, title: 'Episode 4', runtimeMinutes: 47, watched: true },
      { id: 'sh-5', episodeNumber: 5, title: 'Episode 5', runtimeMinutes: 45, watched: false },
      { id: 'sh-6', episodeNumber: 6, title: 'Episode 6', runtimeMinutes: 49, watched: false },
    ],
  },
  {
    id: 'the-bear',
    source: 'manual',
    sourceShowId: null,
    title: 'The Bear',
    section: 'watching',
    sortOrder: 1,
    withPriya: false,
    currentSeason: 5,
    expanded: false,
    archivedAt: null,
    availableSeasonNumber: null,
    seasons: [{ seasonNumber: 5 }],
    episodes: Array.from({ length: 10 }, (_, index) => ({
      id: `bear-${index + 1}`,
      episodeNumber: index + 1,
      title: `Episode ${index + 1}`,
      runtimeMinutes: 31 + (index % 4) * 3,
      watched: index < 2,
    })),
  },
  {
    id: 'the-lowdown',
    source: 'manual',
    sourceShowId: null,
    title: 'The Lowdown',
    section: 'queued',
    sortOrder: 0,
    withPriya: true,
    currentSeason: 1,
    expanded: false,
    archivedAt: null,
    availableSeasonNumber: null,
    seasons: [{ seasonNumber: 1 }],
    episodes: Array.from({ length: 8 }, (_, index) => ({
      id: `lowdown-${index + 1}`,
      episodeNumber: index + 1,
      title: `Episode ${index + 1}`,
      runtimeMinutes: 49 + (index % 3) * 2,
      watched: false,
    })),
  },
  {
    id: 'alien-earth',
    source: 'manual',
    sourceShowId: null,
    title: 'Alien: Earth',
    section: 'queued',
    sortOrder: 1,
    withPriya: false,
    currentSeason: 1,
    expanded: false,
    archivedAt: null,
    availableSeasonNumber: null,
    seasons: [{ seasonNumber: 1 }],
    episodes: Array.from({ length: 8 }, (_, index) => ({
      id: `alien-${index + 1}`,
      episodeNumber: index + 1,
      title: `Episode ${index + 1}`,
      runtimeMinutes: 50 + (index % 2) * 4,
      watched: false,
    })),
  },
  {
    id: 'black-rabbit',
    source: 'manual',
    sourceShowId: null,
    title: 'Black Rabbit',
    section: 'queued',
    sortOrder: 2,
    withPriya: true,
    currentSeason: 1,
    expanded: false,
    archivedAt: null,
    availableSeasonNumber: null,
    seasons: [{ seasonNumber: 1 }],
    episodes: Array.from({ length: 8 }, (_, index) => ({
      id: `rabbit-${index + 1}`,
      episodeNumber: index + 1,
      title: `Episode ${index + 1}`,
      runtimeMinutes: 48 + (index % 4) * 2,
      watched: false,
    })),
  },
  {
    id: 'completed-demo',
    source: 'manual',
    sourceShowId: null,
    title: 'Completed Show',
    section: 'archived',
    sortOrder: 0,
    withPriya: true,
    currentSeason: 2,
    expanded: false,
    archivedAt: '2026-08-24T20:30:00-04:00',
    availableSeasonNumber: 3,
    seasons: [{ seasonNumber: 2, completedAt: '2026-08-24T20:30:00-04:00' }],
    episodes: [],
  },
];
